### PR TITLE
Completely rewrite `gather` 

### LINKED ISSUE #2: Tons of `PermissionDenied` is showed if ddu tried to list the home directory on macOS
It's quite difficult to say it is a bug on this plugin but if there are some directories that you don't have permissions, it shows errors like `PermissionDenied: Operation not permitted (os error 1), reddir '...'`.

Usually, it's not a problem but when I use ddu on my home directory, it shows tons of that because macOS has some special directories on the home directory (like Pictures, Documents, or whatever that require additional permission requests)

CleanShot 2022-02-19 at 22 05 48

So I wonder if the plugin just ignore that errors.

### PR DESCRIPTION
**Pull request by lambdalisue**
- Support cancel
- Ignore `PermissionDenied`
- Accelerate frist view

### Before

https://user-images.githubusercontent.com/546312/154805403-4328cbda-c7b3-4721-a302-76408c48092d.mp4

### After

https://user-images.githubusercontent.com/546312/154808819-62c4aba0-3559-4b06-b88e-e1a460806799.mp4

### CODE REVIEW

**Comment by lambdalisue** [comment]
Note that we should use https://github.com/denoland/deno_std/pull/1939 once it has merged.

**Comment by Shougo** [comment]
Merged.

**Comment by Shougo** [comment]
Oh, it has two fatal problems!

* The gather items are too slow than previous version
* It cannot gather items in root directory.  home directory is OK.

I should revert the changes?

**Comment by Shougo** [comment]
> It cannot gather items in root directory. home directory is OK.

I have fixed the problem.

**Comment by Shougo** [comment]
> The gather items are too slow than previous version

The previous version: 2.81 seconds
HEAD: 7.02 seconds

I have improved chunkSize behavior: 4.20 seconds

**Pull request merged**
